# Generated by Django 4.2.1 on 2023-06-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0002_alter_feedbackdelete_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='meetings_id',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
