# Generated by Django 4.2.1 on 2023-06-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0003_feedback_meetings_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='meetings_id',
            field=models.IntegerField(),
        ),
    ]
