# Generated by Django 4.2.1 on 2023-05-29 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('log_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('log_desc_1', models.CharField(max_length=300, null=True)),
                ('log_desc_2', models.CharField(max_length=300, null=True)),
                ('log_host', models.CharField(max_length=30)),
                ('log_user', models.CharField(max_length=20)),
                ('log_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
