# Generated by Django 4.2.1 on 2023-05-30 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('feedback_name', models.CharField(max_length=100, verbose_name='Nome')),
                ('feedback_message', models.TextField(verbose_name='Mensagem')),
                ('feedback_date_created', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('feedback_evaluation', models.IntegerField(default=0, verbose_name='Avaliações')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackDelete',
            fields=[
                ('fd_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fd_ip', models.CharField(max_length=100, verbose_name='Ip')),
                ('fd_browser', models.CharField(max_length=50)),
                ('fd_date_deleted', models.DateTimeField(auto_now_add=True, verbose_name='Data de Deleção')),
                ('fd_name', models.CharField(max_length=100, verbose_name='Nome')),
                ('fd_message', models.TextField(verbose_name='Mensagem')),
                ('fd_date_created', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('fd_evaluation', models.IntegerField(default=0, verbose_name='Avaliações')),
            ],
        ),
    ]
