# Generated by Django 4.2.1 on 2023-05-29 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PdiDeletion',
            fields=[
                ('pd_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pd_ip', models.CharField(max_length=20)),
                ('pd_browser', models.CharField(max_length=100)),
                ('pd_date_deletion', models.DateTimeField(auto_now_add=True)),
                ('pd_id_pdi', models.CharField(max_length=10)),
                ('pd_skill', models.CharField(max_length=45)),
                ('pd_goal', models.CharField(max_length=45)),
                ('pd_action', models.CharField(max_length=45)),
                ('pd_time', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='PdiDeletionLog',
        ),
        migrations.DeleteModel(
            name='PdiLog',
        ),
    ]
