# Generated by Django 4.2.1 on 2023-05-30 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdi', '0002_pdideletion_delete_pdideletionlog_delete_pdilog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdi',
            name='pdi_action',
            field=models.CharField(max_length=45, verbose_name='Ação'),
        ),
        migrations.AlterField(
            model_name='pdi',
            name='pdi_goal',
            field=models.CharField(max_length=45, verbose_name='Meta'),
        ),
        migrations.AlterField(
            model_name='pdi',
            name='pdi_skill',
            field=models.CharField(max_length=45, verbose_name='Habilidade'),
        ),
        migrations.AlterField(
            model_name='pdi',
            name='pdi_time',
            field=models.DateField(verbose_name='Prazo'),
        ),
        migrations.AlterField(
            model_name='pdideletion',
            name='pd_action',
            field=models.CharField(max_length=45, verbose_name='Ação'),
        ),
        migrations.AlterField(
            model_name='pdideletion',
            name='pd_browser',
            field=models.CharField(max_length=100, verbose_name='Navegador'),
        ),
        migrations.AlterField(
            model_name='pdideletion',
            name='pd_date_deletion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de deleção'),
        ),
        migrations.AlterField(
            model_name='pdideletion',
            name='pd_goal',
            field=models.CharField(max_length=45, verbose_name='Meta'),
        ),
        migrations.AlterField(
            model_name='pdideletion',
            name='pd_id_pdi',
            field=models.CharField(max_length=10, verbose_name='ID do PDI'),
        ),
        migrations.AlterField(
            model_name='pdideletion',
            name='pd_ip',
            field=models.CharField(max_length=20, verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='pdideletion',
            name='pd_skill',
            field=models.CharField(max_length=45, verbose_name='Habilidade'),
        ),
        migrations.AlterField(
            model_name='pdideletion',
            name='pd_time',
            field=models.DateField(verbose_name='Prazo'),
        ),
    ]
