# Generated by Django 4.2.2 on 2023-06-19 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CasaAlugada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_pessoa', models.CharField(blank=True, max_length=100)),
                ('dia_alugou', models.CharField(blank=True, max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Casas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_casa', models.CharField(blank=True, max_length=70)),
                ('valor', models.FloatField()),
            ],
        ),
    ]
