# Generated by Django 4.2.1 on 2023-05-30 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meetings',
            fields=[
                ('meetings_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('meetings_manager_name', models.CharField(max_length=45)),
                ('meetings_collaborator_name', models.CharField(max_length=45)),
                ('meetings_title', models.CharField(max_length=50)),
                ('meetings_desc', models.CharField(max_length=150)),
                ('meetings_local', models.CharField(max_length=50)),
                ('meetings_date', models.DateField(blank=True, null=True)),
                ('meetings_time', models.TimeField(blank=True, null=True)),
                ('meetings_link', models.CharField(blank=True, max_length=200)),
                ('meetings_status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MeetingsDeletion',
            fields=[
                ('md_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('md_ip', models.CharField(max_length=100)),
                ('md_browser', models.CharField(max_length=100)),
                ('md_deletion_date', models.DateTimeField(auto_now_add=True)),
                ('md_id_meeting', models.CharField(max_length=50)),
                ('md_manager_name', models.CharField(max_length=45)),
                ('md_collaborator_name', models.CharField(max_length=45)),
                ('md_title', models.CharField(max_length=50)),
                ('md_desc', models.CharField(max_length=150)),
                ('md_local', models.CharField(max_length=50)),
                ('md_date', models.DateField(blank=True, null=True)),
                ('md_time', models.TimeField(blank=True, null=True)),
                ('md_link', models.URLField(blank=True, null=True)),
                ('md_status', models.CharField(max_length=100)),
            ],
        ),
    ]
