# Generated by Django 4.2.1 on 2023-05-25 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pdi',
            fields=[
                ('pdi_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pdi_skill', models.CharField(max_length=45)),
                ('pdi_goal', models.CharField(max_length=45)),
                ('pdi_action', models.CharField(max_length=45)),
                ('pdi_time', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PdiDeletionLog',
            fields=[
                ('pdi_del_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pdi_date_deletion', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PdiLog',
            fields=[
                ('pdi_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pdi_ip', models.GenericIPAddressField()),
                ('pdi_browser', models.CharField(max_length=100)),
                ('pdi_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
